### ISSUE TITLE
NodeBB v1.10.0 无法使用

### ISSUE THREAD

**Issue by cuteSakuraHime** [NodeBB-China/nodebb-plugin-sso-qq-fix#11]
后台log提示csrf出错

**Comment by cuteSakuraHime** [comment]
`2018-06-30T14:10:12.088Z [28193] - error: /auth/qq/callback
 Error: [[error:csrf-invalid]]
    at router.get.req.session.registration (/root/nodebb/src/routes/authentication.js:75:54)
    at Layer.handle [as handle_request] (/root/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/nodebb/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at /root/nodebb/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/nodebb/node_modules/express/lib/router/index.js:335:12)
    at next (/root/nodebb/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/nodebb/node_modules/express/lib/router/index.js:174:3)
    at router (/root/nodebb/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/nodebb/node_modules/express/lib/router/index.js:317:13)
    at /root/nodebb/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/nodebb/node_modules/express/lib/router/index.js:335:12)
    at next (/root/nodebb/node_modules/express/lib/router/index.js:275:10)
    at /root/nodebb/node_modules/express/lib/router/index.js:635:15`

**Comment by a632079** [comment]
I will fix it in 3 days.

**Comment by greenhat616** [comment]
项目暂停更新. ID: A632079 已被封禁

**Comment by greenhat616** [comment]
我已经修复了此问题。

-----------
这里解释下为何维护迟缓。
本人高中狗。 明年高考， 在江苏竞争。 空余时间较少，对你的长时间等待深感抱歉。
